# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

I1_Cpp <- function(X, k) {
    .Call('symmetry_I1_Cpp', PACKAGE = 'symmetry', X, k)
}

I2_Cpp <- function(X) {
    .Call('symmetry_I2_Cpp', PACKAGE = 'symmetry', X)
}

I2HU_Cpp <- function(X) {
    .Call('symmetry_I2HU_Cpp', PACKAGE = 'symmetry', X)
}

K1_Cpp <- function(X, k) {
    .Call('symmetry_K1_Cpp', PACKAGE = 'symmetry', X, k)
}

K2_get_samples <- function(X) {
    .Call('symmetry_K2_get_samples', PACKAGE = 'symmetry', X)
}

K2U_get_samples <- function(X) {
    .Call('symmetry_K2U_get_samples', PACKAGE = 'symmetry', X)
}

