# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BHI_Cpp <- function(X) {
    .Call('_symmetry_BHI_Cpp', PACKAGE = 'symmetry', X)
}

BHK_Cpp <- function(X) {
    .Call('_symmetry_BHK_Cpp', PACKAGE = 'symmetry', X)
}

CH_Cpp <- function(X) {
    .Call('_symmetry_CH_Cpp', PACKAGE = 'symmetry', X)
}

CM_Cpp <- function(X) {
    .Call('_symmetry_CM_Cpp', PACKAGE = 'symmetry', X)
}

HG_Cpp <- function(X, k, t, H) {
    .Call('_symmetry_HG_Cpp', PACKAGE = 'symmetry', X, k, t, H)
}

I1_Cpp <- function(X, k_in) {
    .Call('_symmetry_I1_Cpp', PACKAGE = 'symmetry', X, k_in)
}

K1_Cpp <- function(X, k_in) {
    .Call('_symmetry_K1_Cpp', PACKAGE = 'symmetry', X, k_in)
}

K2_get_samples <- function(X) {
    .Call('_symmetry_K2_get_samples', PACKAGE = 'symmetry', X)
}

K2U_get_samples <- function(X) {
    .Call('_symmetry_K2U_get_samples', PACKAGE = 'symmetry', X)
}

KS_Cpp <- function(X) {
    .Call('_symmetry_KS_Cpp', PACKAGE = 'symmetry', X)
}

L1_Cpp <- function(X, a) {
    .Call('_symmetry_L1_Cpp', PACKAGE = 'symmetry', X, a)
}

NAI_Cpp <- function(X, k_in) {
    .Call('_symmetry_NAI_Cpp', PACKAGE = 'symmetry', X, k_in)
}

NAK_Cpp <- function(X, k_in) {
    .Call('_symmetry_NAK_Cpp', PACKAGE = 'symmetry', X, k_in)
}

WCX_Cpp <- function(X) {
    .Call('_symmetry_WCX_Cpp', PACKAGE = 'symmetry', X)
}

randomize_sign <- function(X, mu) {
    .Call('_symmetry_randomize_sign', PACKAGE = 'symmetry', X, mu)
}

sample_with_replacement <- function(x, n) {
    .Call('_symmetry_sample_with_replacement', PACKAGE = 'symmetry', x, n)
}

reflect_sample <- function(X, mu, n) {
    .Call('_symmetry_reflect_sample', PACKAGE = 'symmetry', X, mu, n)
}

reflected_boot <- function(X, mu) {
    .Call('_symmetry_reflected_boot', PACKAGE = 'symmetry', X, mu)
}

trimmed_mean <- function(X, alpha = 0) {
    .Call('_symmetry_trimmed_mean', PACKAGE = 'symmetry', X, alpha)
}

boot_sample <- function(X, trim_alpha, B, null_method, stat, k = 0L) {
    .Call('_symmetry_boot_sample', PACKAGE = 'symmetry', X, trim_alpha, B, null_method, stat, k)
}

mn_boot_sample <- function(X, trim_alpha, B, stat, k = 0L, q = 8.0/9) {
    .Call('_symmetry_mn_boot_sample', PACKAGE = 'symmetry', X, trim_alpha, B, stat, k, q)
}

lm_resid <- function(X, yr) {
    .Call('_symmetry_lm_resid', PACKAGE = 'symmetry', X, yr)
}

boot_sample_lm <- function(model_matrix, fitted, residuals, B, null_method, stat, k = 0L) {
    .Call('_symmetry_boot_sample_lm', PACKAGE = 'symmetry', model_matrix, fitted, residuals, B, null_method, stat, k)
}

simulate_garch <- function(resid, y, cfit, omega, alpha, beta) {
    .Call('_symmetry_simulate_garch', PACKAGE = 'symmetry', resid, y, cfit, omega, alpha, beta)
}

