# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

chunk_sum <- function(comb, x, k) {
    .Call('symmetry_chunk_sum', PACKAGE = 'symmetry', comb, x, k)
}

I1_Cpp <- function(X, k) {
    .Call('symmetry_I1_Cpp', PACKAGE = 'symmetry', X, k)
}

